### ISSUE TITLE
Align sideway seperator line with the inner side of the tabs

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#6]

**Comment by liana-yang** [comment]
I am sorry that I cannot solve it. Because there are two probable ways. One way is canceling the borders of the panel manager, and using the borders of the content part. But the height of the content part would change while scrolling. It is inefficient f I used jQuery to fix the height of the div with adding the length of scrollTop(). Another way is using the tab part to overlap part of the left and the bottom border to make the line look like at the inner side. However, the similar problem exists on the tab part while scrolling. Besides, the bottom left corner would leave a part with white background, which would cover the view when it moved to this area, since the div cannot set to be transparent only partly.

I fixed the css style a little bit to make it look better. Let me know if you have any idea to solve this problem. It costs me much time and I decide to move on now. I will try to fix it with other UI design problems together at the end of the project.

**Comment by yubowenok** [comment]
Would it be possible to make the tabs floating on the left, and just make the panel body narrower in width? In that case you can keep all the borders.

Suppose the side panel body is 200px wide and is positioned at "left: 0px". The you can make the tab floating -30px "left: -30px". Because the tabs are floating, they do not interfere with the side panel at all. The side panel body will determine its borders at left=0px and left=200px, so that you don't have a vertical line stroke downwards.

**Comment by liana-yang** [comment]
I tried this way and I am sorry that it doesn't work. The transparent problem solved but the height of the panel content stays unchanged, so that the bottom border would move up while scrolling.

**Comment by liana-yang** [comment]
Even though we can split the panel tab from the panel content and float the panel tab to the left, but we need scrollbar to the whole panel manager. The only way to keep the bottom border all the time is using the bottom border of the panel manager, because the height of the panel content wouldn't increase while scrolling without the control of JS and the bottom border would move up.

**Comment by yubowenok** [comment]
I might be missing sth. What if the side panel has fixed size and the tabs are floating and appended to its left? I don't think the tab would affect the scrolling of the side panel body.

**Comment by liana-yang** [comment]
It is possible as I mentioned before. We can use jQuery scrollTop() to fix the
height of panel body dynamically while scrolling. But it is not intuitive
and it would consume a lot of computing resources.

On Saturday, 7 November 2015, Bowen Yu notifications@github.com wrote:

> I might be missing sth. What if the side panel has fixed size and the tabs
> are floating and appended to its left? I don't think the tab would affect
> the scrolling of the side panel body.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ViDA-NYU/genotet/issues/6#issuecomment-154635756.

## 

_With kind regards,_

_------------------------------------------------------------_

_Liana Yang_

_New York University (NYU)_

_E-mail: shauroshanying http://goog_522613122@gmail.com
http://@gmail.com_

**Comment by yubowenok** [comment]
I mean I still didn't get why making the tabs floating will result in a scroll problem. Maybe you can leave it for now and I will take a closer look tmrw.

**Comment by liana-yang** [comment]
The scrollbar would control the element it belongs to. The panel body would move up and down while scrolling the panel tab, because the scrollbar cannot only control the panel tab (expect set the scrollbar to the panel tab separately near it). Thus the only way to keep the panel body relatively static to the screen is to fix its height. However, fixing the height of panel body dynamically is just like applying gas pedal and break at the same time. Wasting resources like this doesn't make any sense. Thus, I think it is meaningless.

On Saturday, 7 November 2015, Liana Yang shauroshanying@gmail.com wrote:

> It possible as I mentioned before. We can use jQuery scrollTop() to fix
> the height of panel body dynamically while scrolling. But it is not
> intuitive and it would consume a lot of computing resources.
> 
> On Saturday, 7 November 2015, Bowen Yu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > I might be missing sth. What if the side panel has fixed size and the
> > tabs are floating and appended to its left? I don't think the tab would
> > affect the scrolling of the side panel body.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ViDA-NYU/genotet/issues/6#issuecomment-154635756.
> 
> ## 
> 
> _With kind regards,_
> 
> _------------------------------------------------------------_
> 
> _Liana Yang_
> 
> _New York University (NYU)_
> 
> _E-mail: shauroshanying http://goog_522613122@gmail.com
> http://@gmail.com_

## 

_With kind regards,_

_------------------------------------------------------------_

_Liana Yang_

_New York University (NYU)_

_E-mail: shauroshanying http://goog_522613122@gmail.com
http://@gmail.com_

**Comment by yubowenok** [comment]
I'm not saying that we shall control the scroll dynamically. But if the panel body is a sibling of the tabs, and the scroll is on the panel body only, the scroll should not affect the tabs at all. It won't be necessary to scroll the tabs...

**Comment by yubowenok** [comment]
I took a brief look on my phone and it is the case that the tabs are inside the slider div. however I believe they shouldn't...

**Comment by liana-yang** [comment]
I tried move them outside and the problem still exists.......

Maybe we can leave it now temporarily and move on to the expression view
asap......

On Saturday, 7 November 2015, Bowen Yu notifications@github.com wrote:

> I took a brief look on my phone and it is the case that the tabs are
> inside the slider div. however I believe they shouldn't...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ViDA-NYU/genotet/issues/6#issuecomment-154646518.

## 

_With kind regards,_

_------------------------------------------------------------_

_Liana Yang_

_New York University (NYU)_

_E-mail: shauroshanying http://goog_522613122@gmail.com
http://@gmail.com_

**Comment by yubowenok** [comment]
Ok I'll try to fix it.
